"""First revision

Revision ID: 74915bfb5da7
Revises: 
Create Date: 2022-02-25 10:20:55.990936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74915bfb5da7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_total_earnings'), 'user', ['total_earnings'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('coin',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coin_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_amount'), 'coin', ['amount'], unique=False)
    op.create_index(op.f('ix_coin_coin_name'), 'coin', ['coin_name'], unique=False)
    op.create_index(op.f('ix_coin_id'), 'coin', ['id'], unique=False)
    op.create_index(op.f('ix_coin_purchase_price'), 'coin', ['purchase_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_purchase_price'), table_name='coin')
    op.drop_index(op.f('ix_coin_id'), table_name='coin')
    op.drop_index(op.f('ix_coin_coin_name'), table_name='coin')
    op.drop_index(op.f('ix_coin_amount'), table_name='coin')
    op.drop_table('coin')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_total_earnings'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
